<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:busex="http://www.everythingeverywhere.com/common/message/BusinessException/v1.0"
	xmlns:techex="http://www.everythingeverywhere.com/common/message/TechnicalException/v1.0"
	targetNamespace="http://www.everythingeverywhere.com/common/message/FaultMessage/v1.0">

	<documentation>Fault Message v1.0. This file must be imported by every WSDL for consistent use of SOAP Faults.</documentation>

	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.everythingeverywhere.com/common/message/FaultMessage/v1.0">

			<import schemaLocation="BusinessException.xsd"
				namespace="http://www.everythingeverywhere.com/common/message/BusinessException/v1.0" />
			
			<import schemaLocation="TechnicalException.xsd"
				namespace="http://www.everythingeverywhere.com/common/message/TechnicalException/v1.0" />
		</schema>
	</types>

	<message name="technicalFault">
		<part name="fault" element="techex:technicalException" />
	</message>

	<message name="businessFault">
		<part name="fault" element="busex:businessException" />
	</message>
</definitions>